name: maskpls
channels:
  - conda-forge
  - anaconda
dependencies:
  - conda-forge::python=3.8
  - conda-forge::pip
  - anaconda::openblas-devel
  - pip:
    - torch==1.11.0+cu113
    - torchvision==0.12.0+cu113
    - --extra-index-url https://download.pytorch.org/whl/cu113
    - -r requirements.txt
